apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - github.com:argoproj/argo-cd.git/manifests/ha/cluster-install?ref=v2.11.2
  - argocd-namespace.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-redis-ha-haproxy-cm.yaml
generatorOptions:
  disableNameSuffixHash: true
